# Generated by Django 3.2.20 on 2023-07-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_callbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callbooking',
            name='disable_time',
        ),
        migrations.RemoveField(
            model_name='callbooking',
            name='disabled_dates',
        ),
        migrations.RemoveField(
            model_name='callbooking',
            name='enable_time',
        ),
        migrations.RemoveField(
            model_name='callbooking',
            name='enabled_dates',
        ),
        migrations.AddField(
            model_name='callbooking',
            name='day_status_evalible',
            field=models.IntegerField(choices=[(0, 'Enable'), (1, 'Disable')], default=0),
        ),
        migrations.AddField(
            model_name='callbooking',
            name='time_status_evalible',
            field=models.IntegerField(choices=[(0, 'Enable'), (1, 'Disable')], default=0),
        ),
    ]
