# Generated by Django 3.2.20 on 2023-07-31 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20230731_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbooking',
            name='call_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
