# Generated by Django 3.2.20 on 2023-07-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_callbooking_call_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbooking',
            name='call_time',
            field=models.TimeField(null=True),
        ),
    ]
