# Generated by Django 3.2.20 on 2023-08-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20230801_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callbooking',
            name='booked_time_slots',
        ),
        migrations.RemoveField(
            model_name='callbooking',
            name='day_status_evalible',
        ),
        migrations.RemoveField(
            model_name='callbooking',
            name='time_status_evalible',
        ),
    ]
